name: Build and Test Module Updates in Bluehost Plugin
on:
  push:
    branches:
      - main
      - master
      - trunk
      - develop
      - release/*
      - feature/*
      - add/*
      - update/*
      - fix/*
      - try/*
  pull_request:
    types: [ opened, reopened, ready_for_review ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

  bluehost:
    name: Build and Test on Bluehost
    needs: setup
    uses: newfold-labs/action-module-plugin-test/.github/workflows/main.yml@main
    with:
      module-repo: ${{ github.repository }}
      module-branch: ${{ steps.extract_branch.outputs.branch }}
      plugin-repo: 'bluehost/bluehost-wordpress-plugin'

  hostgator:
    name: Build and Test on HostGator
    needs: setup
    uses: newfold-labs/action-module-plugin-test/.github/workflows/main.yml@main
    with:
      module-repo: ${{ github.repository }}
      module-branch: ${{ steps.extract_branch.outputs.branch }}
      plugin-repo: 'newfold-labs/wp-plugin-hostgator'
