name: Crowdin Upload Action

on:
  workflow_dispatch:

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  call-crowdin-upload-workflow:
    uses: newfold-labs/workflows/.github/workflows/i18n-crowdin-upload.yml@main
    permissions:
      contents: write      # Required so the Crowdin GitHub Action can use GITHUB_TOKEN for repository writes during upload.
      pull-requests: write # Required so the Crowdin GitHub Action can use GITHUB_TOKEN for pull request operations when needed.
    with:
      CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
    secrets:
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
